server:
  # 端 口
  port: 6666
#  servlet:
#    context-path: /jeeasy

# 数据源配置
spring:
  ai:
    openai:
      api-key: sk-43e3f0a374c64e1ca2929fb827de80f1
      chat:
        #        base-url: https://dashscope.aliyuncs.com/compatible-mode/
        base-url: http://127.0.0.1:11434/
        api-key: sk-43e3f0a374c64e1ca2929fb827de80f1
        options:
          model: 'qwen-max'
          temperature: 0.7
    ollama:
      base-url: http://127.0.0.1:11434/
      chat:
        options:
          model: qwen2
          temperature: 0.7
          top-k: 50
  # ------- SSO-模式三相关配置 （下面的配置在SSO模式三并且 is-slo=true 时打开） -------
  # 是否打开模式三
  isHttp: true
  # 接口调用秘钥（用于SSO模式三的单点注销功能）
  secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
  # ---- 除了以上配置项，你还需要为 Sa-Token 配置http请求处理器（文档有步骤说明）
  path:
    base: /**
    common-exclude:
      - /sso/doLogin
      - /api-docs/**
      - /swagger-ui/**
      - /webjars/**
      - /doc.html
      - /favicon.ico
    exclude:
      - /api/fn/member/login
      - /api/fn/member/register
    rules:
      - path: /api/fn/**
        roles:
          - ROLE_FN_MEMBER

  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher
  #true为使用 CGLIB 代理，false为JDK代理，默认为false
  #  aop:
  #    proxy-target-class: true
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://data_jeeasy.cn:3306/jeeasy?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123123
          driver-class-name: com.mysql.cj.jdbc.Driver
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  data:
    redis:
      host: data_jeeasy.cn
      #password: KaK6Jm55PLaJyWtW
      port: 6379
      database: 10
      lettuce:
        pool:
          max-active: 8
          max-wait: 1ms
          max-idle: 8
          min-idle: 0

sa-token:
  # -------------- SSO-模式一相关配置  (非模式一不需要配置)
  # cookie:
  # 配置Cookie作用域
  # domain: stp.com

  # ------- SSO-模式二相关配置
  sso:
    # Ticket有效期 (单位: 秒)，默认五分钟
    ticket-timeout: 300
    # 所有允许的授权回调地址
    allow-url: "*"
    # 是否打开单点注销功能
    is-slo: true

    # ------- SSO-模式三相关配置 （下面的配置在SSO模式三并且 is-slo=true 时打开） -------
    # 是否打开模式三
    isHttp: true
    # 接口调用秘钥（用于SSO模式三的单点注销功能）
    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # ---- 除了以上配置项，你还需要为 Sa-Token 配置http请求处理器（文档有步骤说明）
  path:
    base: /**
    common-exclude:
      - /sso/doLogin
      - /api-docs/**
      - /swagger-ui/**
      - /webjars/**
      - /doc.html
      - /favicon.ico
    exclude:
      - /api/fn/member/login
      - /api/fn/member/register
    rules:
      - path: /api/fn/**
        roles:
          - ROLE_FN_MEMBER


mybatis-plus:
  # org.jeeasy.system.modules.user.mapper
  mapper-locations:
    - classpath*:org/jeeasy/**/mapper/xml/*Mapper.xml
    - classpath*:mapper/*Mapper.xml
  check-config-location: true
  type-aliases-package: org.jeeasy.**.domain
  #  type-enums-package: org.jeeasy.**.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # logging 配置
#   logging:
#     # 日 志 级 别
#     level:
#       # 日 志 包 配 置
#       org.jeeasy.*: DEBUG

logging:
  # 日 志 级 别
  level:
    # 日 志 包 配 置
    org.jeeasy.*: DEBUG
    com.lt.crm.service.api: DEBUG

# actable的原配置信息仅保留了如下几项
# MPE以在代码中对其做了默认配置，正常无需显式声明配置，忽略即可
# 如果手动指定了，将覆盖MPE中的默认值

# 启动模式
# none：系统不做任何处理。
# create：系统启动后，会先将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
# update：系统启动后，会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据(更改字段名称的情况下，会认为是新增字段)。
# add：系统启动后，只做新增，比如新增表/新增字段/新增索引/新增唯一约束的功能，而不会去做修改和删除的操作。

mpe:
  auto-table:
    mode: update
    # 您的model包路径，多个路径可以用分号或者逗号隔开，会递归这个目录下的全部目录中的java对象，支持类似com.bz.**.entity
    model-package: org.jeeasy.**.domain
    # 数据库类型，目前也仅支持mysql
    # database:
    #   type: mysql
    # 自己定义的索引前缀，该配置项不设置默认使用actable_idx_
    index-prefix: jeeasy_idx_
    # 自动删除名称不匹配的字段：强烈不建议开启，会发生丢失数据等不可逆的操作。
    auto-drop-column: false
    # 是否自动删除名称不匹配的索引
    auto-drop-index: true
    # # 自己定义的唯一约束前缀，该配置项不设置默认使用actable_uni_
    # unique:
    #   prefix: jeeasy_uni_

springdoc:
  api-docs:
    #是否开启文档功能
    enabled: true
    #swagger后端请求地址
    path: /api-docs
  swagger-ui:
    path: /doc.html
    # 禁止默认路径
    disable-swagger-default-url: true
  group-configs:
    #分组名
    - group: system
      #按路径匹配
      packages-to-scan: org.jeeasy.system.modules
      display-name: 系统管理
      #分组名
    - group: common
      #按包路径匹配
      packages-to-scan: org.jeeasy.common
      display-name: 公共接口
    - group: 统一认证
      #按包路径匹配
      paths-to-match: /sso/*
      display-name: 统一认证
    - group: generate
      #按包路径匹配
      packages-to-scan: org.jeeasy.generate
      display-name: 代码生成

jeeasy:
  dict:
    dict-table-flag: ["@", "#"]
    dict-text-suffix: _dict
    # 根据属性名称自动翻译字典，无需注释 @Dict
    auto-translate-enum-class:
      - org.jeeasy.common.core.enums.EnableFlagEnum
      - org.jeeasy.common.core.enums.DelFlagEnum
      - org.jeeasy.common.core.enums.SexEnum
  modules:
    system:
      # 登录图片验证码开关
      enable-captcha: false
  cache:
    manager:
      # cache自定义键 过期时间
      configs:
        - key: menu
          second: 300
        - key: user
          second: 1800
  #  system:
  #    enable-captcha: false