<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jeeasy</artifactId>
        <groupId>mobie.alps</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>jeeasy-entrance</artifactId>
    <name>启动模块</name>


    <properties>
        <application.main.class>org.jeeasy.JeeasyEntranceApplication</application.main.class>
    </properties>

    <!-- 依赖管理 -->
    <dependencies>
        <dependency>
            <groupId>mobie.alps</groupId>
            <artifactId>jeeasy-generator</artifactId>
        </dependency>
        <!-- 模块引用 -->
        <dependency>
            <groupId>mobie.alps</groupId>
            <artifactId>jeeasy-system-biz</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>mobie.alps</groupId>
            <artifactId>jeeasy-ai-api</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>standalone</id>
            <dependencies>
                <dependency>
                    <groupId>mobie.alps</groupId>
                    <artifactId>jeeasy-ai-biz</artifactId>
                    <version>${revision}</version>
                </dependency>
            </dependencies>
            <!-- 构建工具 -->
            <build>
                <plugins>
                    <!-- 选择性地启用父级模块中的插件 -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-assembly-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>