<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jeeasy</artifactId>
        <groupId>mobie.alps</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>jeeasy-entrance</artifactId>
    <name>启动模块</name>


    <properties>
        <application.main.class>org.jeeasy.JeeasyEntranceApplication</application.main.class>
    </properties>

    <!-- 依赖管理 -->
    <dependencies>
        <dependency>
            <groupId>mobie.alps</groupId>
            <artifactId>jeeasy-generator</artifactId>
        </dependency>
        <!-- 模块引用 -->
        <dependency>
            <groupId>mobie.alps</groupId>
            <artifactId>jeeasy-system-biz</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>mobie.alps</groupId>
            <artifactId>jeeasy-ai-api</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>standalone</id>
            <dependencies>
                <dependency>
                    <groupId>mobie.alps</groupId>
                    <artifactId>jeeasy-ai-biz</artifactId>
                    <version>${revision}</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

    <!-- 构建工具 -->
    <build>
        <sourceDirectory>src/main/java</sourceDirectory>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*Mapper.xml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>*.properties</include>
                    <include>*.yml</include>
                    <include>**/*.xml</include>
                    <include>*.jet</include>
                    <include>*.bat</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>scripts/**</exclude>
                    <exclude>sdk/**</exclude>
                    <exclude>*.properties</exclude>
                    <exclude>*.yml</exclude>
                    <exclude>**/*.xml</exclude>
                    <exclude>*.jet</exclude>
                </excludes>
            </resource>


            <!-- 收集运行脚本 -->
            <resource>
                <directory>.../scripts</directory>
                <targetPath>${project.build.directory}/bin</targetPath>
                <filtering>true</filtering>
                <includes>
                    <include>*.sh</include>
                    <include>*.bat</include>
                </includes>
            </resource>
            <!-- 收集配置文件 -->
            <resource>
                <directory>src/main/resources</directory>
                <targetPath>${project.build.directory}/conf</targetPath>
                <filtering>true</filtering>
                <excludes>
                    <exclude>**/rebel.xml</exclude>
                    <exclude>**/scripts/**</exclude>
                </excludes>
                <includes>
                    <include>**/*.yml</include>
                    <include>**/*.xml</include>
                    <include>**/*.vm</include>
                    <include>**/*.properties</include>
                </includes>
            </resource>

            <!-- 收集静态资源文件 -->
            <resource>
                <directory>src/main/resources/static</directory>
                <targetPath>${project.build.directory}/static</targetPath>
            </resource>

            <!-- 收集sdk文件 -->
            <resource>
                <directory>src/main/resources/sdk</directory>
                <targetPath>${project.build.directory}/sdk</targetPath>
            </resource>

            <!-- 收集手动导入的jar包 -->
            <resource>
                <directory>lib</directory>
                <targetPath>${project.build.directory}/lib</targetPath>
            </resource>
        </resources>
        <plugins>
            <!-- <plugin> -->
            <!-- <artifactId>maven-war-plugin</artifactId> -->
            <!-- <version>3.0.0</version> -->
            <!-- </plugin> -->

            <!-- 2.用于生成jar包的plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <outputDirectory>${project.build.directory}/lib</outputDirectory>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                        </manifest>
                    </archive>
                    <excludes>
                        <exclude>static/**</exclude>
                        <exclude>*.properties</exclude>
                        <exclude>*.yml</exclude>
                        <exclude>*.xml</exclude>
                        <exclude>*.jet</exclude>
                    </excludes>
                </configuration>
            </plugin>

            <!-- 3.用于拷贝maven依赖(lib)的plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.8.0</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- 打包zip -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>zip</id>
                        <configuration>
                            <archive>
                                <manifest>
                                    <mainClass>${application.main.class}</mainClass>
                                </manifest>
                            </archive>
                            <descriptors>
                                <descriptor>../scripts/assembly.xml</descriptor>
                            </descriptors>
                            <outputDirectory>./target/zip/${profiles.active}/</outputDirectory>
                            <finalName>${project.name}-${project.version}</finalName>
                        </configuration>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>