server:
  # 端 口
  port: 9000

# 数据源配置
spring:
  datasource:
    dynamic:
      datasource:
        # 主库数据源
        master:
          url: jdbc:mysql://mobie.vip:3306/jeeasy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: jeeasy
          password: 26yMBG8hRRNKrEMT