server:
  # 端 口
  port: 8888

# 数据源配置
spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://mobie.vip:3306/jeeasy?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: jeeasy
          password: 26yMBG8hRRNKrEMT
          driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: mobie.vip
    password: KaK6Jm55PLaJyWtW
    port: 6379
    database: 10

mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jeeasy:
  # 权 限 配 置
  security:
    # 不 需 要 权 限 拦 截 的 接 口 配 置
    open-api:
      - /login/**  # 开放 登录 接口
      - /noUser  # 开放 未登录重定向 接口
      - /noAuth  # 开放 权限不足重定向 接口
      - /captcha/** # 开放 验证码生成 接口
      #      - /assets/** # 开放 静态资源
      #      - /admin/** # 开放 静态资源
      #      - /component/** # 开放 静态资源
      - /favicon.ico # 开放 Logo
      # swagger 排除
      - /doc.html
      - /webjars/**
      - /swagger-resources
      - /v2/api-docs
    login-url: /noUser
    login-processing-url: /login
    logout-url: /logout
  swagger:
    enable: true
    module:
      jeeasy-system:
        group-name: Jeeasy 系统管理
        title: Jeeasy 系统管理接口 API文档
        version: 1.0
        base-package: org.jeeasy.system.modules
      jeeasy-common:
        group-name: Jeeasy 公共接口
        title: Jeeasy 公共接口 API文档
        version: 1.0
        base-package: org.jeeasy.common
        annotation: org.springframework.web.bind.annotation.RequestMapping
#      jeeasy-online:
#        groupName: Jeeasy 在线开发
#        title: Jeeasy 在线开发 API接口文档
#        version: 1.0
#        basePackage: org.jeeasy.online