server:
  # 端 口
  port: 8888

# 数据源配置
spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://mobie.vip:3306/jeeasy?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: jeeasy
          password: 26yMBG8hRRNKrEMT
          driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jeeasy:
  swagger:
    enable: true
    defaultModule: jeeasy-system
    module:
      jeeasy-system:
        groupName: Jeeasy 系统管理
        title: Jeeasy 系统管理 API接口文档
        version: 1.0
        basePackage: org.jeeasy.system
#      jeeasy-online:
#        groupName: Jeeasy 在线开发
#        title: Jeeasy 在线开发 API接口文档
#        version: 1.0
#        basePackage: org.jeeasy.online
